### ISSUE TITLE
Measurement Heading color need to change in dark theme

### ISSUE THREAD

**Issue by DarpanLalani** [Cumulocity-IoT/cumulocity-advanced-radial-gauge-widget-plugin#1]
Check in the attached example

![MicrosoftTeams-image (2)](https://github.com/SoftwareAG/cumulocity-advanced-radial-gauge-widget-plugin/assets/32765455/c33d3e05-4ad3-4570-bbc3-5196d05f9bbb)

Please verify and fix if required if reproducible with blueprint forge and app builder 2.1

**Comment by YashPShah-swag** [comment]
Color selector given for heading color. version 1.2.1.
