### ISSUE TITLE
Add Last measurement date at bottom

### ISSUE THREAD

**Issue by DarpanLalani** [Cumulocity-IoT/cumulocity-advanced-radial-gauge-widget-plugin#2]
![image](https://github.com/SoftwareAG/cumulocity-advanced-radial-gauge-widget-plugin/assets/32765455/8f6e0de7-42e4-4c00-bfba-95af9c241424)

**Comment by YashPShah-swag** [comment]
Last updated date added on top. version 1.2.0.
